### PR TITLE
Allow the Ledger Device to display Scilla Data as its being streamed to the device

### LINKED ISSUE #1: Verbose smart contract transaction display on the Ledger Nano S
When signing transactions on the blockchain, the Zilliqa app for the Ledger Nano S displays the `recipient`, `amount` and `gas price` associated with that transaction. The transaction is signed once the user confirms these details. The transaction to be signed is protobuf encoded on the host (computer) side and streamed to the device. The device simultaneously applies the Schnorr signature algorithm on the data being stream, as well as decodes parts of the protobuf object to display the three fields mentioned above.

For smart contract transactions, the `data` to be displayed (Scilla transition parameters) can be arbitrarily long. 
- The Zilliqa app currently on the ledger store does not attempt to display additional details for smart contract transactions.
- On our GitHub repository, we have an experimental branch that attempts to parse the transition parameter JSON (which is inside the protobuf encoded transaction). However, the stack and global memory limitations of the Ledger Nano S limits the length of transition parameters that can be displayed in these smart contract transactions.

The app today is designed such that it accumulates the message to be displayed, while data (protobuf object) is being streamed to it (and is also being passed to the Schnorr algorithm). Once streaming is done, the details are displayed on screen, confirmed and then the signature (which was also accumulated, but not transferred to the host) is displayed and sent to the host. This design fundamentally limits the length of the details we can display on the device for user confirmation.

Therefore, the **goal of this project** will be to:
- Redesign the UI of the app such that, while it streams (and decodes) the protobuf data for Schnorr signing, it also displays parts of the transition message parameters JSON as it sees them, have the part confirmed by the user and then proceed to stream more message parameters. 
(i.e. multi step approval process: display first half, user approval returns 0x9000, display second half, user approval returns whatever you need)
- As a more ambitious goal, the JSON can be parsed and the transition parameters displayed in a more readable way, but this is secondary, and it may be ok to display the raw JSON as-is for the above.

An example of a valid smart contract transaction payload for signing can be found below for ease of testing:
```
{
  "version": 65537,
  "nonce": 43,
  "toAddr": "6E263953C92b12060Fd73885FC56e300631591F9",
  "amount": 0,
  "gasPrice": 1000000000,
  "gasLimit": 40000,
  "code": "",
  "data": "{ \"_tag\":\"SubmitCustomTransferFromTransaction\", \"params\":[{\"vname\":\"proxyTokenContract\",\"type\":\"ByStr20\",\"value\":\"0x6e263953c92b12060fd73885fc56e300631591f9\"},{\"vname\":\"from\",\"type\":\"ByStr20\",\"value\":\"0x5abf71d798ca594b7317b04f52ad5a31fae62170\"},{\"vname\":\"to\",\"type\":\"ByStr20\",\"value\":\"0x5420599c5d62c00b69675cfccf5f14627c1693c5\"},{\"vname\":\"value\",\"type\":\"Uint128\",\"value\":\"10000000\"}]}"
}
```

### PR DESCRIPTION
**Pull request by mul1sh**
Will fix #1

### CODE REVIEW

**Comment by mul1sh** [comment]
As follow-up to parsing the JSON object, i've been trying to do it using [Jasmine](https://github.com/zserge/jsmn) and honestly don't think its possible to do so in a nano S.

Will keep researching though :)

**Comment by vaivaswatha** [comment]
@mul1sh . Thank you very much.

I had attempted a JSON decoding, but only when the `data` field was less than a limit (around 256 bytes), beyond which it would give up. 

1. The current latest is the branch `displaytxn`, **can you rebase your PR against that**?
2. The branch `displaytxn` pretty much does the same thing as your PR, but only when `data` fits in a limited size buffer, and if not, gives up. Your PR on the other hand, I assume, can display the same information, but for arbitrarily long `data` field.
3. Regarding decoding the JSON (for limited sized ones). here is the change that removed that functionality: https://github.com/Zilliqa/ledger-app-zilliqa/commit/167f6ef8560bde2f516983b89d8fa70b42732715 You can checkout a version before that and see. I'm sure you can re-use a lot of the JSON decoding code there in case you come up with a plan to decode the JSON on your PR.

**Comment by vaivaswatha** [comment]
>can you rebase your PR against that?

Let me elaborate.
1. Your PR provides the same functionality as that branch (but is better because it doesn't restrict data length). My branch however has a few other changes related to adding stack canary checks which I think should be on `master` ultimately.
2. I suggest waiting for a couple of days to do this. The plan is that I merge `displaytxn` to `master` first and you can rebase after that. I'm waiting for the Ledger guys to merge that branch to their fork of the repo.

**Comment by mul1sh** [comment]
@vaivaswatha no worries thanks for clarifying. Yes my PR makes to possible to read a data field of any length 🙂.

So anyway I'll rebase on the `displaytxn` branch as advised and also try to make it work with JSON decoding over this weekend and then close this PR and make another one.

Also why should I wait for the master merge or for the ledger guys to merge? The changes in master will still be the same, regardless of either merge, no? 🤔

**Comment by vaivaswatha** [comment]
>The changes in master will still be the same, regardless of either merge, no? thinking
Hopefully, yes. Ledger guys have reviewed the PR and they are fine with it, so I don't expect changes. With that assumed, it should be fine if you rebase from `displaytxn`. In the worst case that they suggest more changes, then you may have to rebase again (but even then, I expect only minor changes).

So yes, do go ahead with rebasing from `displaytxn`.

**Comment by mul1sh** [comment]
Awesome thanks will do 🙂

**Comment by mul1sh** [comment]
Closing this in favour of #5 as agreed

**Pull request closed without merging**
